# ------ root_path/dataset_name ------
root_path: 'DATA'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [30, 30]
search_step: [200, 20]

init_beta: 1
init_alpha: 5
init_theta: 0.33


# ------ Basic Config ------
dataset: 'fgvc'
shots: 4
backbone: 'RN50'

lr: 0.0002
augment_epoch: 10
train_epoch: 180