# ------ root_path/dataset_name ------
root_path: 'DATA'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [10, 10]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17
init_theta: 0.3

# ------ Basic Config ------
dataset: 'food101'
shots: 4
backbone: 'RN50'
# backbone: 'RN50x16'

lr: 0.0005
augment_epoch: 10
train_epoch: 20